# -*- coding: utf-8 -*-
"""TTS-App Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqsuVqs9eeFFqOkT1t9q_t5ggeurzes5
"""

!pip install gradio requests

# ✅ Import libraries
import gradio as gr
import requests

# 🔐 My ElevenLabs API Key
api_key = "sk_dbd30006ef30e7421bee43c8dc5312f1b309df8d27b9be51"

# 🎙 Voice Options - Replace with actual voice IDs from ElevenLabs
voice_options = {
    "Nigeria (Female)": "WjC4A2cTO3MVjWo1GIkW"
}

# 🔊 Text-to-Speech Function
def tts_generate(text, voice_name):
    voice_id = voice_options.get(voice_name)
    if not voice_id:
        return None, None

    url = f"https://api.elevenlabs.io/v1/text-to-speech/{voice_id}"
    headers = {
        "xi-api-key": api_key,
        "Content-Type": "application/json"
    }
    payload = {
        "text": text,
        "voice_settings": {
            "stability": 0.5,
            "similarity_boost": 0.7
        }
    }

    response = requests.post(url, headers=headers, json=payload)

    if response.status_code != 200:
        print("API Error:", response.text)
        return None, None

    # Save audio to file
    audio_path = "nigerian_tts_output.mp3"
    with open(audio_path, "wb") as f:
        f.write(response.content)

    return audio_path, audio_path

# 🎨 Gradio App UI
with gr.Blocks() as app:
    gr.Markdown("## 🗣 Nigeria English Text-to-Speech App")
    gr.Markdown("Convert your English 🔤 to sweet voice 🎧 using AI!")

    with gr.Row():
        text_input = gr.Textbox(label="✍ Enter English Text", placeholder="When he removed them now, did they ignore the removal?")
        voice_dropdown = gr.Dropdown(choices=list(voice_options.keys()), label="🎙 Choose a Voice")

    generate_btn = gr.Button("🔊 Generate Audio")

    audio_output = gr.Audio(label="🎧 Audio Player")
    download_output = gr.File(label="⬇ Download Audio")

    generate_btn.click(
        fn=tts_generate,
        inputs=[text_input, voice_dropdown],
        outputs=[audio_output, download_output]
    )

# 🚀 Launch the App
app.launch(share=True)